### ISSUE TITLE
Project status?

### ISSUE THREAD

**Issue by janderedev** [revoltchat/rvmob#12]
Hi, are you still working on this?

The last commit was made in December last year and I haven't seen you around on Revolt either - Is this project dead?

Me and many others are looking forward to having a proper mobile client. If you no longer want to work on rvmob, please let us know :)

**Comment by TaiAurori** [comment]
I was originally planning on making a Flutter rewrite of RVMob, but the necessity of engineering an entirely new library in combination with personal problems led to the project becoming dormant. I'll likely be returning to the React Native version when I get back around to making contributions, we just need to revise the structure of the codebase a bit ;)

**Comment by janderedev** [comment]
Sounds great! If you need help, I'm down to contributing.
