### ISSUE TITLE
Add cross-instance functionality

### ISSUE THREAD

**Issue by TaiAurori** [revoltchat/rvmob#14]
### What do you want to see?

Add a rudimentary form of switching the API path used by the app, so situations like [this](https://github.com/ggtylerr/dvmob) don't need to occur.

**Comment by Rexogamer** [comment]
This is *almost* done - however, at the moment the custom instance URL isn't being loaded in time; still trying to figure out a solution to this

**Comment by Rexogamer** [comment]
This has now been added; you can specify a custom instance, and once the app is reloaded it will connect to it - however, it's a *bit* clunky and the support is pretty basic so I'm not 100% sure whether I want to enable this by default in the next version

**Comment by ggtylerr** [comment]
Hey, thank you guys for adding it :) Not sure why this is now the _only_ client that supports multi instance, but it's a start!

Also, why'd you guys rebase off of my fork 😅 Not mad or anything, I just think it's funny how I'm now technically a contributor (even though I basically didn't do anything)

**Comment by Rexogamer** [comment]
You bumped a bunch of deps at one point and had a much more extensive README; I think at the time I wanted to save some time (as I was also unsure as to whether I was going to continue maintaining the project in a fork or here)

**Comment by ggtylerr** [comment]
I don't remember doing that, I think I just ran `yarn` lol

**Comment by ggtylerr** [comment]
It seems integration is a little buggy. Using it with Divolt results in a boot loading loop upon reloads, editing messages with a 400 (sometimes?), and whatever _this_ is whenever you send something:
![Screenshot_20230503-051416_RVMob Canary.jpg](https://user-images.githubusercontent.com/28498877/235877386-763e3dd4-d3a6-49d8-b392-fe0b70962e4a.jpg)

I'm not sure where the relevant logfiles are and pressing debug just crashes the app, so here are the screenshots from warnings:
_Upon reloading and attempting to log in_
![Screenshot_20230503-051037_RVMob Canary.jpg](https://user-images.githubusercontent.com/28498877/235877789-63db9bcc-bbfb-42b6-98ac-08e50194cb83.jpg)
 _Upon editing a message (maybe its just char limit? idk)_
![Screenshot_20230503-051241_RVMob Canary.jpg](https://user-images.githubusercontent.com/28498877/235877998-405e3a81-6dcb-4c95-90b3-f54489acf43f.jpg)
_Upon pressing "Debug"_
![Screenshot_20230503-051910_RVMob Canary.jpg](https://user-images.githubusercontent.com/28498877/235878205-cbe44ade-3892-4e67-a728-fedc961579e2.jpg)
![Screenshot_20230503-051915_RVMob Canary.jpg](https://user-images.githubusercontent.com/28498877/235878204-ff444da1-9bde-4fd2-8f76-ccc68106c7d4.jpg)

**Comment by Rexogamer** [comment]
I suspect it might not've logged in properly, although I'll have to do further debugging; however, last time I tried to set up a Divolt account it seemingly just kept erroring so hmm

**Comment by ggtylerr** [comment]
> ...however, last time I tried to set up a Divolt account it seemingly just kept erroring so hmm

If it was a database error, it's Divolt's side. There's some bug in the DB that sometimes causes it to crash. We just have it on an hourly restart for now. (Of course, it's good to check if you're able to login on the website first)

**Comment by Rexogamer** [comment]
I managed to log in without any issues on a test account so hmmm

**Comment by ggtylerr** [comment]
> I managed to log in without any issues on a test account so hmmm

Reloads work?

**Comment by Rexogamer** [comment]
?

**Comment by ggtylerr** [comment]
Does restarting the app log in properly on your end, or does it result in a promise rejection, like this: ![Screenshot_20230505-133037_RVMob Canary.jpg](https://user-images.githubusercontent.com/28498877/236526562-71a47ac9-5a25-4f8a-b376-b6f24aebabca.jpg)

**Comment by ggtylerr** [comment]
> Good catch - that issue should be fixed in bc41588. I haven't encountered any other issues though 🤔

Thank you. I'm getting a different error now, though. This one occurs on the login screen regardless of restarts. Tried reinstall too. Not sure why this is occuring, might try it on WSA later.
![Screenshot_20230505-151050_RVMob Canary.jpg](https://user-images.githubusercontent.com/28498877/236549360-2c7cd913-76fd-4c14-848c-294ff4020821.jpg)


> Also, regarding [your fork](https://GitHub.com/fmhy/dvmob) of RVMob, is it mostly just to change the URLs? If so, it might be worth upstreaming support for them in some way but hmm

Basically, yeah. Since RVMob now supports instance switching, we'll probably stop working on DVMob and recommend people to use this instead.
(also note - this technically isnt my fork anymore since I transferred ownership to FMHY)

**Comment by Rexogamer** [comment]
That error seems to be related to certificates - I haven't seen it locally so it *might* be a Divolt issue but I'm not 100% sure

> Basically, yeah. Since RVMob now supports instance switching, we'll probably stop working on DVMob and recommend people to use this instead.

Sounds good ^^

**Comment by MasicoreLord** [comment]
> That error seems to be related to certificates - I haven't seen it locally so it _might_ be a Divolt issue but I'm not 100% sure
> 
> > Basically, yeah. Since RVMob now supports instance switching, we'll probably stop working on DVMob and recommend people to use this instead.
> 
> Sounds good ^^

Wouldn't an easy fix, be to explicitely disable any certificate pinning?  Then you don't have to worry about certificate errors, as it'd then fallback to whatever the os or user ended up trusted.

**Comment by MasicoreLord** [comment]
In-case you were thinking of publishing RVMob to the play store, I even searched to see if omitting client certificate pinning would stop it from getting approved, and seems it's not a requirement, and even discouraged to be used as a solution according to this article:
https://developer.android.com/training/articles/security-ssl

**Comment by Rexogamer** [comment]
RVMob doesn't pin any certificates directly so I'm not sure where this issue is coming from

**Comment by ggtylerr** [comment]
> That error seems to be related to certificates - I haven't seen it locally so it _might_ be a Divolt issue but I'm not 100% sure

I think it was, I'm not getting it anymore. Maybe the spaghetti code somehow fixed itself or the hourly restart fixed it, idk...

**Comment by MasicoreLord** [comment]
> RVMob doesn't pin any certificates directly so I'm not sure where this issue is coming from



> > That error seems to be related to certificates - I haven't seen it locally so it _might_ be a Divolt issue but I'm not 100% sure
> 
> I think it was, I'm not getting it anymore, both on WSA and on my Note 10. Maybe the spaghetti code somehow fixed itself or the hourly restart fixed it, idk...
> 
> Subsequent restarts do work, though, so at least that's fixed :D

odd, in either case, this may have clues on how to possibly prevent it:
https://docs.oracle.com/javase/8/docs/api/java/security/cert/CertPathValidatorException.html

**Comment by Rexogamer** [comment]
I'm gonna close this issue as completed. The final polishing work will be listed in another issue; if you encounter any issues, either open another issue or let me know in [the RVMob server](https://rvlt.gg/ZFGGw6ry)
