### ISSUE TITLE
bug: New messages occasionally fail to render until the channel is reopened

### ISSUE THREAD

**Issue by taotao2008** [revoltchat/rvmob#15]
### What happened?
Hello there! 
Send  a message NO display. Chat window must be reopened to see this messages.
![WechatIMG858](https://user-images.githubusercontent.com/10294984/230847982-e19fefcd-21af-4672-91b1-9b3cc514383b.jpeg)
![WechatIMG863](https://user-images.githubusercontent.com/10294984/230883202-ab082c21-4fb2-4ff7-8264-b872c261633e.jpeg)

![WechatIMG861](https://user-images.githubusercontent.com/10294984/230848407-2b09186f-6341-4d44-942c-33e87872d311.jpeg)

**Comment by Rexogamer** [comment]
Known issue - it seems to happen frequently but inconsistently, and I'm still trying to figure out why exactly

**Comment by Rexogamer** [comment]
Update: I *think* I've fixed this by removing a broken check - I'm keeping an eye out for any side effects, but it seems to be working fine (apart from the fact that it doesn't automatically scroll when new messages appear, but you can just scroll down to see them so this isn't *as* urgent)

**Comment by Rexogamer** [comment]
(Temporarily re-opening while I monitor for any feedback in this regard; will close if everything is fine)

**Comment by taotao2008** [comment]
That's great! After testing , it already can been used, now this app experience is much better!

**Comment by Rexogamer** [comment]
Great to hear - if you find any other issues, please feel free to open a new issue. Thanks! ^^
