### ISSUE TITLE
feature request: desktop client? gentoo ebuild?

### ISSUE THREAD

**Issue by petaflot** [revoltchat/rvmob#30]
### What do you want to see?

I find the documentation of this github somewhat lacking and obscure.

I will maintain gentoo ebuilds if someone here is willing to assist me getting to know the revolt ecosystem

cheers

**Comment by Rexogamer** [comment]
RVMob doesn't currently support any platforms other than Android - did you mean to file this under another Revolt repo?

**Comment by petaflot** [comment]
what do I know? I just found out there was an "alternative" to discord, that it was not packaged, that there were mentions of "only on Android" (which is really lame if I may say), I'm ok to maintain a client and/or server ebuild for gentoo but there are some 2 dozens repos about revolt and not even a short concise view of the global architecture.

**Comment by account0123** [comment]
discussions about project here https://github.com/orgs/revoltchat/discussions/

**Comment by Rexogamer** [comment]
> not packaged
For Gentoo? If so, you'll want Revolt Desktop (`revoltchat/desktop`); I think you might've missed the README of this repo which says 
![image](https://github.com/revoltchat/rvmob/assets/42586271/fc42fee5-f491-41a8-9b7c-d6132f107516)

>there were mentions of "only on Android" (which is really lame if I may say)
This only applies to RVMob, which is what this repo contains. I do not have a Mac and therefore have no ability to bring RVMob to iOS at this time. We are separately working on official Android and iOS clients (RVMob is a community project), and there's already Revite (a web app, accessible at https://app.revolt.chat).

> not even a short concise view of the global architecture
With all due respect, the organisation README visibly contains [a list of our repos](https://github.com/revoltchat#repositories) and descriptions of what each one contains:
![image](https://github.com/revoltchat/rvmob/assets/42586271/3b5a3e27-cd5d-4ed6-9733-5568a77713f4)
![image](https://github.com/revoltchat/rvmob/assets/42586271/f901a6dc-5f81-4ce7-aad9-3e432ce35ab1)

I don't really know what other information I can give at the moment; if you have any other questions, I would advise using the link @account0123 provided.
